### ISSUE TITLE
BUG: 启用ssr渲染，naive-ui存在刷新时UI偏移问题 

### ISSUE THREAD

**Issue by hb0730** [hb0730/T-Nav#13]
[20240627170806.webm](https://github.com/hb0730/T-Nav/assets/33956166/a699ceda-2e5c-4486-ad5d-ba51f9652082)

相关问题

https://github.com/tusen-ai/naive-ui/issues/5326

修复如下: 

https://github.com/07akioni/css-render/issues/1108

依赖
```
"@css-render/vue3-ssr": "^0.15.14",
 "css-render": "^0.15.14",
```

plugins
```
import { setup } from '@css-render/vue3-ssr'

/**
 * fix 
 */
export default defineNuxtPlugin((nuxtApp) => {
  const { collect } = setup(nuxtApp.vueApp)
  useServerHead({
    style: () => {
      const stylesString = collect()
      const stylesArray = stylesString.split(/<\/style>/g).filter(style => style)
      return stylesArray.map((styleString: string) => {
        const match = styleString.match(/<style cssr-id="([^"]*)">([\s\S]*)/)
        if (match) {
          const id = match[1]
          return { 'cssr-id': id, 'children': match[2] }
        }
        return {}
      })
    },
  })
})
```

待上游修复

**Comment by huoliwei** [comment]
增加插件后有警告[Vue warn]: App already provides property with key "@css-render/vue3-ssr". It will be overwritten with the new value.你有遇到这个问题吗？

**Comment by hb0730** [comment]
这种方式确实会有警告，可以看看[@bg-dev/nuxt-naiveui](https://github.com/becem-gharbi/nuxt-naiveui/)
